### ISSUE TITLE
Does not recognize the interface

### ISSUE THREAD

**Issue by Pikapollo3000** [TheBATeam/Batch-WI-FI-Brute-Forcer#10]
Pls fix it
![Captura de pantalla 2024-12-08 200946](https://github.com/user-attachments/assets/e0cffcc8-dead-4f7a-a019-7a5a88f7d81f)

**Comment by lioen-dev** [comment]
You need to have more interfaces installed to be able to select them. If you did download them and they are in the correct directory but still do not show up, let me know and I'll try to help.

**Comment by Pikapollo3000** [comment]
> You need to have more interfaces installed to be able to select them. If you did download them and they are in the correct directory but still do not show up, let me know and I'll try to help.

how do I download them?

**Comment by lioen-dev** [comment]
write your own, download some from forks or search from github. as far as i know theres no central database for interfaces

**Comment by Pikapollo3000** [comment]
> write your own, download some from forks or search from github. as far as i know theres no central database for interfaces

idk how to do it,my interface is my wifi card??

**Comment by lioen-dev** [comment]
i was understanding your question incorrectly. if your motherboard has wifi built in, it should be recognized. if its a 3rd party wifi card/usb, you might need to install drivers or do other steps from the manufacturers website to get it to be recognized by the bruteforcer. hope this helps.

**Comment by Marcothepolo55** [comment]
> i was understanding your question incorrectly. if your motherboard has wifi built in, it should be recognized. if its a 3rd party wifi card/usb, you might need to install drivers or do other steps from the manufacturers website to get it to be recognized by the bruteforcer. hope this helps.

do you know where is the manufacturers website ? i cant find it

**Comment by lioen-dev** [comment]
no, i dont know the manufacturer's website because i do not know who
manufacturers your motherboard or wifi card.

**Comment by TheKvc** [comment]
@Pikapollo3000 answer is mentioned here... https://github.com/TheBATeam/Batch-WI-FI-Brute-Forcer/issues/7#issuecomment-2539161334
