### ISSUE TITLE
how to install interface

### ISSUE THREAD

**Issue by literallywhyyy** [TheBATeam/Batch-WI-FI-Brute-Forcer#12]
no interface found on this device

**Comment by lioen-dev** [comment]
if you have wifi built in to your motherboard, it should automatically detect but if you are using a 3rd party wifi usb/card, you may need to install drivers or follow instructions on the manufacturer's website to get it to be recognized by the program.

**Comment by TheKvc** [comment]
Pull request with FIX from @lioen-dev is integrated. thankyou for contributing. (I was the founder of TheBATeam, we have moved on to new platform: batch-man.com)
