### ISSUE TITLE
INTERFACE PROBLEM

### ISSUE THREAD

**Issue by JABIR-EXE** [TheBATeam/Batch-WI-FI-Brute-Forcer#14]
THE FILE CANT TRACK MY INTERFACE WHILE I HAVE CONNECTED TO A WIFI FROM MY MOTHER BOREAD ALL IS INTALLEED IDK WHY HE DIDINT DETECTE NOTHING PLEASE HELP ME
![Uploading Capture d’écran (28).png…]()

**Comment by lioen-dev** [comment]
you may need to install drivers or follow instructions on the manufacturer's website to get it to be recognized by the program.

**Comment by TheKvc** [comment]
Looks like your screenshot is nt uploaded properly. (I was the founder of TheBATeam, we have moved on to new platform: batch-man.com)

**Comment by TheKvc** [comment]
the answer is mentioned in https://github.com/TheBATeam/Batch-WI-FI-Brute-Forcer/issues/7#issuecomment-2539161334

**Comment by JABIR-EXE** [comment]
when i start wifiscan it crashed why

**Comment by TheKvc** [comment]
> when i start wifiscan it crashed why

Can you attach a screenshot???

**Comment by JABIR-EXE** [comment]
is working tnx
