### ISSUE TITLE
error in wifiscan

### ISSUE THREAD

**Issue by Akarsh-dubey** [TheBATeam/Batch-WI-FI-Brute-Forcer#19]
https://github.com/TheBATeam/Batch-WI-FI-Brute-Forcer/blame/93f554dc8762cc188f3b10592e941f4e83f064f4/Source%20Code/bruteforce.cmd#L173

**Comment by Akarsh-dubey** [comment]
when I am scanning wifi  it is showing error

**Comment by ChesterVilleLive** [comment]
Crash after wifiscan command. if i find the fix ill post here. Fing new guy here.

**Comment by Procraft8249MC** [comment]
Change line 399 to:
				if "!current_ssid!"=="" (

and it should work.

**Comment by Procraft8249MC** [comment]
Make sure to add the spaces

**Comment by lioen-dev** [comment]
This issue is fixed in the latest version of the application, redownload and rerun to fix the issue.

**Comment by ChesterVilleLive** [comment]
thank its kind working now i can try it Learn something.
