### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by sixten535** [TheBATeam/Batch-WI-FI-Brute-Forcer#22]
It just crashes directly after i use wifiscan cmd

**Comment by suleim5** [comment]
I also experienced the same problem it’s cuz of hidden network if you add a
line that ignores a hidden network in line 399 you will good to go

**Comment by lioen-dev** [comment]
this issue is fixed in the latest version, so you can just redownload from the repository to fix the issue

**Comment by Procraft8249MC** [comment]
Change line 399 to:
				if "!current_ssid!"=="" (

and add the spaces

**Comment by lioen-dev** [comment]
This issue is fixed in the latest version of the application, just redownload to fix the issue.
