### ISSUE TITLE
interface issues

### ISSUE THREAD

**Issue by ROGER8SA** [TheBATeam/Batch-WI-FI-Brute-Forcer#26]
if i run the CMD its Works perfectly but the problem is that its say ( Interface - not selected ) and when i type ( Interface) it only appears 
( 1- cancel Selection ) what should i do ? 
![image_2024-12-16_204618752](https://github.com/user-attachments/assets/a3c2b368-3327-48d6-80b3-065f5c518658)
![Screenshot 2024-12-16 204601](https://github.com/user-attachments/assets/e20a7402-1605-4873-9b01-73e90ae63a22)

**Comment by lioen-dev** [comment]
you'll need to edit the source code to modify the interface detection code from "Wi-Fi" to "WiFi", or use my repo that has the fix built in. you also need to make sure your language is set to english.

https://github.com/lioen-dev/Batch-WI-FI-Brute-Forcer

**Comment by ROGER8SA** [comment]
I apologize for the inconvenience and for wasting your time, but I am a complete beginner in programming 
I did what you told me and modified the code myself but the problem still exists

**Comment by lioen-dev** [comment]
Hey, it's all good. I'm not at the computer at the moment but if you're
willing to get on a call or email later today I'll try to help figure this
out. I can't help much more without more context/screenshots, etc.
