### ISSUE TITLE
BIG ISSUE 

### ISSUE THREAD

**Issue by Soni-debug** [TheBATeam/Batch-WI-FI-Brute-Forcer#33]
Does it works while using a smartphone???
I'm still scrolling on a row without finding nothing since then🤷🏾‍♂️

**Comment by lioen-dev** [comment]
this script does not work on a smartphone, batch is windows only

**Comment by Soni-debug** [comment]
Oh ok, how stupid I was 😅. Isn't there a or some script which works on
smartphones??
I'm using a HONOR brand phone. Thank you.

Le mer. 25 déc. 2024 à 22:49, Rowan Barker ***@***.***> a
écrit :

**Comment by TechnicalUserX** [comment]
I strongly suggest you to install **Termux** app to your phone from F-Droid. It is basically a terminal emulator for your phone which you may run programs and scripts inside of it.

**Comment by Soni-debug** [comment]
Thank you

Le sam. 28 déc. 2024 à 18:26, Kaan Baydemir ***@***.***> a
écrit :
