### ISSUE TITLE
"importwifi.xml missing, exiting..."

### ISSUE THREAD

**Issue by makromanp** [TheBATeam/Batch-WI-FI-Brute-Forcer#39]
what do i do when this happens?

**Comment by TechnicalUserX** [comment]
Could you please provide more information about the issue?

**Comment by makromanp** [comment]
i open the .cmd and it gives me that message, then it closes. Do i need to change something in the .xml file?

**Comment by makromanp** [comment]
never mind i fixed it, thx anyways

**Comment by makromanp** [comment]
fixed
