### ISSUE TITLE
There's a bug with network scan

### ISSUE THREAD

**Issue by Kazkaaz** [TheBATeam/Batch-WI-FI-Brute-Forcer#5]
This guy explains it in yt... https://youtu.be/HoEGN7dKqC0?si=FDY0Mk104SX_aBur&t=230

Thank you!

**Comment by lioen-dev** [comment]
This issue has already been fixed in the latest version.

**Comment by TheKvc** [comment]
The latest changes has been accepted. (I was the founder of TheBATeam, we have moved on to new platform: batch-man.com)
