### ISSUE TITLE
There is no interface 

### ISSUE THREAD

**Issue by Maloute431** [TheBATeam/Batch-WI-FI-Brute-Forcer#7]
When i type interface nothing shows up. I'm connected to wifi via an Intel(R) Wi-Fi 6 AX200 160MHz. Do you know howw to fix ?
![Capture d'écran 2024-12-08 115406](https://github.com/user-attachments/assets/3ad1e1eb-4dba-4ae1-a1a1-a273d573bf2c)

**Comment by lioen-dev** [comment]
You need to have more interfaces installed to be able to select them. If you did download them and they are in the correct directory but still do not show up, let me know and I'll try to help.

**Comment by literallywhyyy** [comment]
Can you tell me how to download the interface?

**Comment by Maloute431** [comment]
i have a wifi key that i connected via usb into my pc but still nothing

**Comment by lioen-dev** [comment]
There is no specific download link for interfaces because they are
unnecessary as far as I've found, you can just use the default. None will
show up just by plugging in a wifi card, etc.

**Comment by lioen-dev** [comment]
Don't quote me on this because I'm not at my computer currently. I'll edit
my message once I'm home

**Comment by Maloute431** [comment]
But what do I have to do now ? I wanna use thsis but i don't know how

**Comment by lioen-dev** [comment]
apologies for the delay. i was understanding the question incorrectly. if your motherboard has built in wifi, it should be automatically detected by the bruteforcer, but if you are using a 3rd party wifi card/usb thats not built into the mobo you may need to install drivers or do something else to get your interface recognized. check your interface's manufacturer for more details about that.

**Comment by aidengua** [comment]
> apologies for the delay. i was understanding the question incorrectly. if your motherboard has built in wifi, it should be automatically detected by the bruteforcer, but if you are using a 3rd party wifi card/usb thats not built into the mobo you may need to install drivers or do something else to get your interface recognized. check your interface's manufacturer for more details about that.

I don't think so? I'm using laptop, and the interface page still don't shows up my wifi card interface, anyway to fix!

**Comment by lioen-dev** [comment]
sorry about that. if you are using a laptop, it should show up because the wifi is built in to the motherboard. you may have to use a different computer or not use the tool until a fix is proposed. maybe look through the code and make a pull request?

**Comment by TheKvc** [comment]
This issue was solved on our discord server. 
![image](https://github.com/user-attachments/assets/a93d672a-aabd-495b-bdb2-b2b306f2e698)

the brute-force code needs to be updated as one of my good friend @anic17 suggested on discord conversation...

![image](https://github.com/user-attachments/assets/0da7c93e-900a-4e8c-bb50-a21e27db0bee)


run the following command in your cmd and notice if you are seeing 'name' as : WIFI or Wi-Fi (2nd one is expected by program) 

@lioen-dev can you integrate these? if you don't mind (i am not sure when i will get time next)

**Comment by lioen-dev** [comment]
yeah, ill try to implement the code. sorry for the late reply, been busy with school.

**Comment by htann008** [comment]
<img width="388" alt="imageh

**Comment by htann008** [comment]
<img width="388" alt="image" src="https://github.com/user-attachments/assets/83eba81d-d052-490d-a2ce-e77c39f2450e" />

uh, wht is it :v

**Comment by TheKvc** [comment]
This has been fixed
