### ISSUE TITLE
colorchar not recognised 

### ISSUE THREAD

**Issue by theperfectprotagonist** [TheBATeam/Batch-WI-FI-Brute-Forcer#9]
when it try to run the sourcecode file it comes saying 'colorchar.exe' is not recognized as an internal or external command,
operable program or batch file.
anyone know a solution?

**Comment by Maloute431** [comment]
Hey, i got the same problem but i know how to ix it you have to unzip the folder into another folder and it'll work trust me

**Comment by theperfectprotagonist** [comment]
Your are the best thank you so much🫡

**Comment by lioen-dev** [comment]
please remember to mark an issue as resolved if your problem has been fixed.
